services:
  frontend:
    image: gps-upload
    build:
      context: ./Frontend # Ojo: Asegúrate de que tu carpeta se llame así (en tu archivo original decía Proyect-Gest-Docum)
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - backend
    ports:
      - 8065:8065

  backend:
    image: gps-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT: 8064
      # Actualizado a la IP/Dominio de tu servidor institucional
      FRONTEND_ORIGIN: http://pacheco.chillan.ubiobio.cl:8065
      # Apunta al nombre del servicio de la base de datos en Docker
      MONGODB_URI: mongodb://mongodb:27017
      MONGODB_DB: proyecto_gps
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    ports:
      - 8064:8064

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
